;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        go-mode-insert-and-indent
        kill-region
        typescript-insert-and-indent
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        ))
