(thieman-when-not-arm (global-set-key (kbd "M-x") 'smex))
(global-set-key (kbd "C-c w") 'whitespace-mode)
(global-set-key (kbd "C-c j") 'ace-jump-mode)
(global-set-key (kbd "C-c g") 'ag-project)
(global-set-key (kbd "M-s") 'magit-status)
(global-set-key (kbd "C-c p") 'projectile-command-map)
(global-set-key [f11] 'toggle-fullscreen)
