(thieman-when-not-arm (global-set-key (kbd "M-x") 'smex))
(global-set-key (kbd "C-x w") 'whitespace-mode)
(global-set-key (kbd "C-x j") 'ace-jump-mode)
(global-set-key (kbd "C-x g") 'ag-project)
(global-set-key (kbd "C-c C-p") 'compile)
(global-set-key (kbd "M-s") 'magit-status)
(global-set-key [f11] 'toggle-fullscreen)
